name: Test checks

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run script
        run: python main.py
        # continue-on-error: true
      - name: Post error step
        run: echo "::error file=main.py::Post error message"
        if: failure()
