name: Print changes

on:
  pull_request:

jobs:
  print-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Track changes
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          since_last_remote_commit: true
          files: |
            docker-compose.yml
            docker-compose.yaml
      - name: Print changes
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

